version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: roma.pletyk@gmail.com
      PGADMIN_DEFAULT_PASSWORD: roma3333
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
